#!/usr/bin/env bash
main() {
  sudo /usr/bin/pacman -Sy
  cd $HOME/.voithos-caching
  echo "Enter the name of the package you would like to install."
  read VOITHOS_INSTALL
  case "$VOITHOS_INSTALL" in 
    *)
      echo "Preparing for installation of $VOITHOS_INSTALL"
  esac
  https://aur.archlinux.org/$VOITHOS_INSTALL.git
  cd ./$VOITHOS_INSTALL/
  /usr/bin/makepkg -si
  echo -e "\e[1;35mFinished installing "$VOITHOS_INSTALL
  echo "If you would like to remove the package, this is not available in the current version."
  echo "This option will soon be available in future updates."
  echo "Please go to the git repository of Voithos, run git pull and run setup to update Voithos."
  exit
}