#!/usr/bin/env bash
main() {
  sudo /usr/bin/pacman -Sy
  cd $HOME/.voithos-caching
  echo "Enter the name of the package you would like to install."
  read VOITHOS_INSTALL
  case "$VOITHOS_INSTALL" in 
    *)
      echo "Preparing for installation of $VOITHOS_INSTALL"
  esac
  git clone https://aur.archlinux.org/$VOITHOS_INSTALL.git
  cd ./$VOITHOS_INSTALL/
  /usr/bin/makepkg -sri
  echo -e "\e[1;35mFinished executing the installation of "$VOITHOS_INSTALL
  echo "If you would like to remove the package, do so using pacman"
  echo "Please go to the git repository of Voithos, run git pull and run setup to update Voithos."
  exit
}

main
